fix: composite tests input

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2,9 +2,13 @@ name: 'Simple compose service updates'
 description: 'Simple compose service update process for your repos'
 inputs:
   default_branch: 
-    description: 'Path to file'
+    description: 'default branch'
     required: false
     default: 'master'
+  prs:
+    description: 'prs?'
+    required: false
+    default: 'generate'
   skips:
     description: 'Skip some services'
     required: false
@@ -18,5 +22,11 @@ runs:
         default_branch=${{ inputs.default_branch }}
         skips=${{ inputs.skips }}
         prs=${{ inputs.prs }}
+
+        # Validate the 'prs' input
+        if [[ "$prs" != "generate" && "$prs" != "skip" ]]; then
+          echo "Invalid value for 'prs' input. Allowed values are 'generate' or 'skip'."
+          exit 1
+        fi
 
         ${{ github.action_path }}/bin/pincher.sh "$default_branch" "$prs" "$skips"
